trigger:
  branches:
    include:
      - main  # Trigger the pipeline on push to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu for the pipeline

variables:
  voteImage: 'minahiliqbal/vote:latest'  # Docker image for the voting app
  resultImage: 'minahiliqbal/result:latest'  # Docker image for the result app
  workerImage: 'minahiliqbal/worker:latest'  # Docker image for the worker app
  azureResourceGroup: 'ITM-Learning'  # Your Azure Resource Group
  aksClusterName: 'reactapp-cluster'  # Your AKS Cluster Name

steps:

# Checkout the code from the repository
- task: Checkout@2
  displayName: 'Checkout repository'

# Deploy to Azure Kubernetes Service (AKS)
- task: AzureCLI@2
  displayName: 'Deploy to AKS'
  inputs:
    azureSubscription: 'Azure subscription 1'  # Your Azure DevOps Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get AKS credentials
      az aks get-credentials --resource-group $(azureResourceGroup) --name $(aksClusterName) --overwrite-existing

      # Apply the Kubernetes manifests
      kubectl apply -f k8s/deployment.yml
      kubectl apply -f k8s/service.yml

# Get the External IP of the service
- task: Kubernetes@1
  displayName: 'Get AKS External IP'
  inputs:
    connectionType: 'Azure Resource Manager'  # Connection to Azure
    azureSubscription: 'Azure subscription 1'  # Your Azure DevOps Azure service connection
    kubernetesCluster: '$(aksClusterName)'
    namespace: 'default'
    command: 'get'
    arguments: 'svc voting-app-service'

# Output the External IP of the voting app
- script: |
    echo "Fetching external IP for the voting app..."
    kubectl get svc voting-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
  displayName: 'Fetch External IP of Voting App'
